### PR TITLE
fix(serverless-component): when adding primary domain name to CloudFront distribution aliases, don't replace other aliases

### PR DESCRIPTION
**Pull request by dpowell**
I missed this in ea180e67515ee5dceed1c3e19731291615a7cbbb, where the domain alias being added to the distribution would overwrite aliases that were added when we create the distribution. Append the domain alias(es) to the list instead of creating a new Aliases.Items to preserve those.

There don't seem to be any tests for this component, so I manually verified running the built component locally. If I overlooked a test suite that should be updated, let me know.

### CODE REVIEW

**Review by dphang — APPROVED** [review]

**Comment by dphang** [comment]
@dpowell actually now that I think about it I think this may have conflicts by appending to existing aliases, if managing using `domain` inputs, we should let it manage and overwrite all aliases. Will it not keep appending to existing aliases when distribution needs to be updated. So you can end up with multiple entries e.g `["example.com", "example.com"]?

Otherwise if we don't want to use `domain` inputs, then just use the `aliases` input to manage the domains (and set certificate manually).

**Comment by dphang** [comment]
Planning to revert this change in next couple days to original behavior which should be more correct, @dpowell please do let me know if you have any issues or concerns.

**Comment by dpowell** [comment]
The push for the domain’s alias could be conditional on !contains, perhaps. 

It wasn’t clear to me that domain was optional, so I’ve been using domain for my “primary” (even though not using Route53 or ACM for it) and aliases for additional. Perhaps I just read too much into that and we could clarify in a docs setting about aliases to use only one or the other.

**Comment by dphang** [comment]
@dpowell created this to revert to original behavior: https://github.com/serverless-nextjs/serverless-next.js/pull/731. Will do some more manual testing myself. If you can, please pull and build this branch and see if it works well for you still. Thanks!

**Comment by danielcondemarin** [comment]
@dphang Personally I think we should aim to "update" distribution settings rather than "overriding" whenever possible. This is particularly beneficial to those reusing the same distribution for next.js deployments and other APIs that may require different CNAMES etc. Hence why I raised https://github.com/serverless-nextjs/serverless-next.js/issues/477 a while back. 

You're right though, it adds complexity and makes it more difficult to maintain. I think for now we should go with what you suggested and review it once we redo how deployments work in future.

**Pull request merged**
