### PR TITLE
feat: Add domain locale detection for rewrites and non default locales (#1640)

### PR DESCRIPTION
**Pull request by jfernandomeyer**
When my route manifest is something like

```
{
  "locales": ["en", "fr"],
  "defaultLocale": "en",
  "domains": [
    {
      "domain": "domain.com",
      "defaultLocale": "en"
    },
    {
      "domain": "domain.fr",
      "defaultLocale": "fr"
    }
  ],
  rewrites:  [
    {
      source: '/en/:path*/',
      destination: 'https://ext-domain.com/:path*/',
      locale: false,
    },
    {
      source: '/fr/:path*/',
      destination: 'https://ext-domain.fr/:path*/',
      locale: false,
    },
  ],
}
```

The function getRewritePath() appends only the default locale, not considering the i18n domains list locales

## Expected behavior

The function findDomainLocale() should also be used within getRewritePath() so the locale is appended properly for every domain locale.

## Additional context

The Origin domain in the SSR Lambda@Edge by default is the S3 bucket domain configured in the CloudFront distribution. In order to have the domain header propagated properly, you have to change the distribution with the following steps https://aws.amazon.com/premiumsupport/knowledge-center/configure-cloudfront-to-forward-headers/

This PR closes https://github.com/serverless-nextjs/serverless-next.js/issues/1640

### CODE REVIEW

**Comment by jfernandomeyer** [comment]
@dphang can you please support with this PR? I'm trying to use rewrites as a proxy step for our migration project and having this working would be awesome 🙏

**Comment by dphang** [comment]
Thanks for fixing! I hadn't fully tested this (and e2e tests don't have multiple domains yet). I was on vacation but can a look once I'm back tomorrow

**Comment by dphang** [comment]
@jfernandomeyer seems to have failed many of the e2e tests, could you please try to run next-app e2e tests locally and debug the errors in CloudWatch logs (getting many 503s). I'll check the AWS logs as well later.

Run: https://github.com/serverless-nextjs/serverless-next.js/runs/3548777743?check_suite_focus=true

**Comment by dphang** [comment]
NVM, it looks the failures are due to AWS S3 client issue:
```
{
    "errorType": "Error",
    "errorMessage": "AWS CRT binary not present in any of the following locations:\n\t/bin/native/aws-crt-nodejs\n\t/bin/linux-x64/aws-crt-nodejs",
    "stack": [
        "Error: AWS CRT binary not present in any of the following locations:",
        "\t/bin/native/aws-crt-nodejs",
        "\t/bin/linux-x64/aws-crt-nodejs",
        "    at Object.<anonymous> (/var/task/S3Client-26c3ef0b.js:1862:11)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Module.require (internal/modules/cjs/loader.js:961:19)",
        "    at require (internal/modules/cjs/helpers.js:92:18)",
        "    at /var/task/default-handler-42f1fead.js:2476:76",
        "    at async handleOriginResponse (/var/task/default-handler-42f1fead.js:2476:26)",
        "    at async Runtime.handler (/var/task/default-handler-42f1fead.js:2298:20)"
    ]
}
```

Found a related thread in: https://github.com/aws/aws-sdk-js-v3/issues/2750#issuecomment-912800096, upgrading to 3.30 should fix the AWS-CRT issue.

**Comment by dphang** [comment]
Latest e2e run after merging from master LGTM: https://github.com/serverless-nextjs/serverless-next.js/runs/3550007529?check_suite_focus=true

**Review by dphang — APPROVED** [review]

**Comment by jfernandomeyer** [comment]
Hey @dphang, first of all, thanks a lot for reviewing and merging the code.

Could you just give some clarity on how the stable release cadency works? 
I currently face a limitation that I can only bring over stable releases, therefore, this fix would need to be promoted from alpha to 3.4.0.

Any idea when this will happen and what to expect for this alpha promotion every time I contribute?

Thanks a lot for the support
Serverless NextJS is great 😁

**Comment by dphang** [comment]
@jfernandomeyer yes there is no official cadence but I try to promote the release about every month to have some time to bake and be more stable in case of any major issues reported. However all releases do go through a full suite of end-to-end tests, so it should for the most part be "stable".

**Pull request merged**
