### PR TITLE
Pass certificateArn to domain component

### PR DESCRIPTION
**Pull request by huksley**
Currently, declared on README.md page `certificateArn` does not passed to `domain` component, resulting in searching for domain certificate, which works bad for subdomains, i.e. app.example.com

See issue here: https://github.com/serverless-nextjs/serverless-next.js/issues/821

### CODE REVIEW

**Comment by dphang** [comment]
Thanks, since domain component doesn't have any test coverage yet, please test the change if it is working fine, then can merge it.

**Comment by huksley** [comment]
@dphang Would you like me to write a test on it? I am currently deploying it to my infra and it is working.

**Comment by dphang** [comment]
If you have time and it's simple that'd be great (there is an issue for this: https://github.com/serverless-nextjs/serverless-next.js/issues/690), but we may move away from it in the future (looking into more robust IaC tools like CDK). But we can merge this one first. Thanks!

**Comment by dphang** [comment]
Ran e2e tests: https://github.com/serverless-nextjs/serverless-next.js/actions/runs/395710571

**Pull request merged**
