### PR TITLE
#493 fixing S3 307 errors

### PR DESCRIPTION
**Pull request by andrewgadziksonos**
This is a fix for #493 

- Added `originRegion` as an input in `aws-cloudfront`.  This is mapped in from `bucketRegion` in `serverless-component`
- DomainName is set to the region specific URL if `originRegion !== "us-east-1"`
- Updated documentation
- Updated unit-tests

### CODE REVIEW

**Comment by danielcondemarin** [comment]
@andrewgadziksonos Thanks for PR'ing 🙌  

Just a couple of comments from me,

- Seems like the new `originRegion` input doesn't work for multiple S3 input origins.
 
For example:

```yml
distribution:
  component: '@serverless/aws-cloudfront'
  inputs:
    originRegion: us-east-1
    defaults: # optional
    origins:
      - url: https://a-bucket.s3.amazonaws.com
      - url: https://another-bucket.s3.amazonaws.com
         pathPatterns:
            /x/y/z: ...
```

- I think we don't need a new `originRegion` input. Instead users could pass the S3 regional endpoint themselves.

```yml
distribution:
  component: '@serverless/aws-cloudfront'
  inputs:
    origins:
      - url: https://a-bucket.s3.us-east-1.amazonaws.com
      - url: https://another-bucket.s3.eu-west-1.amazonaws.com
         pathPatterns:
            /a/b/c: ...
      - url: https://another-bucket.s3.us-west-2.amazonaws.com
         pathPatterns:
            /d/e/f: ...
```

For that to work the fix could be simply passing `originUrl` to `originConfig.DomainName` in [this line](https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/aws-cloudfront/lib/getOriginConfig.js#L21):
i.e. `originConfig.DomainName = originUrl`

**Comment by andrewgadziksonos** [comment]
> the fix could be simply passing `originUrl` to `ori`

AH!  This makes more sense - I'll work on this asap today

**Comment by andrewgadziksonos** [comment]
@danielcondemarin - changes made

**Comment by danielcondemarin** [comment]
> @danielcondemarin - changes made

Great stuff I'll jump in the branch and take it for a spin

**Pull request merged**
