### PR TITLE
[Documentation][Alpha-Release] - Serverless NextJS component documentation (Available for Preview)

### PR DESCRIPTION
**Pull request by jsphkhan**
`Alpha Release`. `Available for Preview`

**Contributions welcome to the same PR:**

- Clone the repo
- Fetch the branch: `git fetch origin documentation:documentation`
- Make changes
- Commit and Push

**View the docs:**
cd documentation
npm install
npm start

**Doc version**
```bash
"version": "1.0.0",
```

**Demo**
5158f3ff5f52eff0eb0aeca34350954f

**Pending**
1. Search (Algolia) - https://v2.docusaurus.io/docs/search
2. Documentation pages - done
3. Customizations to look n feel and page orders 
4. Remove dark mode - done

### CODE REVIEW

**Comment by jsphkhan** [comment]
@danielcondemarin Need the ability to add labels to PR. Not able to modify (labels on the right). Pls suggest

**Comment by danielcondemarin** [comment]
For the docs I'm thinking of the following structure:

- Serverless Component >
  ... pretty much the Content in the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md)
- Compatibility Layers >
   - CloudFront / Lambda at Edge >
    ... [docs ](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/lambda-at-edge-compat)
   - API Gateway / Lambda
    ... [docs ](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/apigw-lambda-compat)
- Examples 
 
Maybe that's a good starting point?

**Comment by jsphkhan** [comment]
@danielcondemarin Pretty much as you like. I will create the base template and the setup. And then we can modify as you like. Since  the docs will be static rendered pages, you can host them on any SSR services - Netlify, Github Pages.

**Comment by jsphkhan** [comment]
I am moving to Docusaurus 2. Has more features and easier than Docusaurus 1

**Comment by jsphkhan** [comment]
@danielcondemarin Basic docs2 seed structure set up is ready. You can take a look. Lots of work left, I will continue to work on. You can share your thoughts for this initial setup

**Comment by danielcondemarin** [comment]
> @danielcondemarin Basic docs2 seed structure set up is ready. You can take a look. Lots of work left, I will continue to work on. You can share your thoughts on this initial setup.
> 
> Do you use Slack or Discord? I can leave a message there. Much faster!!

Brilliant work! I am currently working on a few other things but will take a look at this as soon as I get a chance. 

I'll add you to our contributors Slack. Ping me on [DM me](https://twitter.com/dcondemarin) and I'll send you an invite link 🙂

**Comment by jsphkhan** [comment]
> > @danielcondemarin Basic docs2 seed structure set up is ready. You can take a look. Lots of work left, I will continue to work on. You can share your thoughts on this initial setup.
> > Do you use Slack or Discord? I can leave a message there. Much faster!!
> 
> Brilliant work! I am currently working on a few other things but will take a look at this as soon as I get a chance.
> 
> I'll add you to our contributors Slack. [DM me](https://twitter.com/dcondemarin) and I'll send you an invite link 🙂

Cool. Awesome...

**Pull request merged**
