### PR TITLE
feat(cloudfront): add ability to set RealtimeLogConfigARN

### PR DESCRIPTION
**Pull request by Raffaello**
this fixes https://github.com/serverless-nextjs/serverless-next.js/issues/2284

this works adding in the configuration yaml:
```yaml
defaults: # optional
        realtimeLogConfigArn: 'the realtime log config ARN'
```

### CODE REVIEW

**Comment by Raffaello** [comment]
hi @dphang 👋 
when you have some time, could you please look into this one? 
thanks.

**Comment by dphang** [comment]
Sure I think it looks fine, though not sure why the CI tests aren't running?

**Review by dphang — APPROVED** [review]

**Comment by Raffaello** [comment]
> Sure I think it looks fine, though not sure why the CI tests aren't running?

@dphang 
I don't know, I can't see details. 
besides i am not authorized to merge the PR.

anyone that can look into that or merging the PR?

**Comment by Raffaello** [comment]
maybe just try to re trigger those 2 circle ci jobs.

**Comment by dphang** [comment]
No worries! I think we can merge and let master CI work

**Pull request merged**
