### PR TITLE
feat(nextjs-component): introduce serverless-patched binary

### PR DESCRIPTION
**Pull request by dphang**
* Recognizes CI environments so that multiple "Deploying ..." messages are not displayed
* Fixes next silent build failure from here https://github.com/serverless-nextjs/serverless-next.js/issues/605

Unfortunately `patch-package` doesn't support multiple patches (so all of it is in one file), but hopefully we don't have many other major fixes.

### CODE REVIEW

**Comment by dphang** [comment]
Hm, so the patching should happen in `postinstall` step which is after the package is pulled but before `serverless` is actually executed. 

Are you running it with `npx serverless-patched` or did you install `@sls-next/serverless-component` and try to run the local `serverless-patched` binary? While testing, the local `serverless-patched` was a bit wonky because of how `node_modules` are linked...sometimes found that `node_modules/@serverless/cli` are not there. Maybe I need to add `@serverless/cli` as a hard dependency instead of just `serverless`?

You could also try `npx --package @sls-next/serverless-component serverless-patched` which will force `npx` to use a temp package, it might take a couple seconds extra to download the component though.

**Comment by csandman** [comment]
I saw your original issue after commenting, and the need to run the command with `serverless-patched` instead.  The way I have it, `@sls-next/serverless-component` is not installed anywhere manually, so it is only pulled during the run of the `serverless` command.  This is my codebuild config:

```yml
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - "touch .npmignore"
      - "npm install -g serverless"
  pre_build:
    commands:
      - "npm install"
  build:
    commands:
      - "serverless --debug"
```

And I have nothing to do with serverless in my `package.json`, relying on having `component: "@sls-next/serverless-component@3.4.0-alpha.3" in my `serverless.yml`. Would I need to have `@serverless/cli` and/or `@sls-next/serverless-component` in my dependencies to make it work?

**Comment by dphang** [comment]
I have fixed the directory resolution and moved it into a separate package. The new command is: `npx @sls-next/serverless-patched --debug`. Just tested in GitHub Actions (with the e2e tests) and it seems to work fine, let me know if there are issues.

**Comment by stan-sack** [comment]
still getting exit code 0 for failed deployment with `3.4.0-alpha.9`. Does that have the change?

**Comment by stan-sack** [comment]
oh right i have to use patched serverless

**Comment by stan-sack** [comment]
it might work. it exits with an error code but the debug logs dont work with the patched version:
```
$ npx @sls-next/serverless-patched --debug --stage=staging
npm WARN exec The following package was not found and will be installed: @sls-next/serverless-patched
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1
```

**Comment by stan-sack** [comment]
yeah i wasnt able to get this running. when i swapped the following in my CI script it broke with the above error
```
-    - npx @sls-next/serverless-patched --cache .npm --debug --stage=staging
+   - npx serverless --cache .npm --debug --stage=staging
```

I have custom `serverless.js` file in my root thats checking the stage flag (as recommended in your documentation). maybe thats breaking it?

**Pull request merged**
