### PR TITLE
Added `x-forwarded-host` as precedence over `host` header

### PR DESCRIPTION
**Pull request by janario**
As started to support at https://github.com/serverless-nextjs/serverless-next.js/pull/1641

This PR added the precedence for `x-forwarded-host` when running behind a reverse proxy.

### CODE REVIEW

**Comment by janario** [comment]
Ready for review  ;-)

**Comment by dphang** [comment]
Hm, this looks fine but seems to have broken the e2e tests: https://github.com/serverless-nextjs/serverless-next.js/runs/4101421933?check_suite_focus=true. Haven't had a chance to investigate but if you could try to deploy to the `next-app` app and test to see what broke, that would be great

**Comment by mathvbarone** [comment]
> Hm, this looks fine but seems to have broken the e2e tests: https://github.com/serverless-nextjs/serverless-next.js/runs/4101421933?check_suite_focus=true. Haven't had a chance to investigate but if you could try to deploy to the `next-app` app and test to see what broke, that would be great

Hey @dphang I am trying to figure out what is going on with the `integration tests`...
I deployed this version of `serverless-nextjs` to a nextjs and I was not able to reproduce the issue, could you please point out what could be wrong, or what steps to reproduce the error? 
Thanks!

**Comment by mathvbarone** [comment]
> > Hm, this looks fine but seems to have broken the e2e tests: https://github.com/serverless-nextjs/serverless-next.js/runs/4101421933?check_suite_focus=true. Haven't had a chance to investigate but if you could try to deploy to the `next-app` app and test to see what broke, that would be great
> 
> Hey @dphang I am trying to figure out what is going on with the `e2e tests`... I deployed this version of `serverless-nextjs` to a nextjs and I was not able to reproduce the issue, could you please point out what could be wrong, or what steps to reproduce the error? Thanks!

Ok, I managed to run it (by following instructions on CONTRIBUTING.md 😅)) and still not sure what is the issue...I rolled back the changes to current `master`, ran the integration tests, and got the same result as with the changes:

image

:/

**Comment by dphang** [comment]
@mathvbarone thanks for taking a look. I will try to take a look myself (probably need to look into the actual lambda logs for the e2e tests to see what's going on)

**Comment by janario** [comment]
Hi 

I've pulled the remote main branch again.

Anything pending on us in the PR?

Thanks,
Janario Oliveira

**Comment by dphang** [comment]
Hm seems the previous issue with E2E tests was transient, it succeeded now. Will merge and publish later after master is green

**Pull request merged**
