### PR TITLE
fix(lambda-at-edge): static regeneration while running in ISR mode #1729

### PR DESCRIPTION
**Pull request by cmaerz**

### CODE REVIEW

**Comment by dphang** [comment]
Looks like some unit tests failed

**Comment by cmaerz** [comment]
@dphang Yeah.. I can‘t get the build running currently. See: #1729
Maybe you can help me there, than I can fix the tests :D

**Comment by dphang** [comment]
Hm, are archiver types added properly? You can also try to delete the yarn lock file temporarily and regenerate it, sometimes it helped me when dependencies are having issues

**Comment by cmaerz** [comment]
Hm.. deleting yarn.lock didn't help. Tbh I don't even know what archiver is, I didn't add that package :D

**Comment by dphang** [comment]
ran e2e tests: https://github.com/serverless-nextjs/serverless-next.js/actions/runs/1268687056

**Review by dphang — APPROVED** [review]

**Review by dphang — APPROVED** [review]

**Pull request merged**
